# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['LhtFile', 'NepalModel']

# Cell
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as TM

# Cell
class LhtFile:
    '''
    capsulate the file name and file path
    '''
    def __init__(self,fileName, filePath):
        self.file_name = fileName
        self.file_path = filePath

# Cell
class NepalModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = TM.resnet34(pretrained=True)
        self.fc2 = nn.Linear(1000,2)
    def forward(self,x):
        x = F.relu(self.encoder(x))
        x = torch.sigmoid(self.fc2(x))
        return x